node {
    stage('Checkout'){
        checkout scm
    }
    stage("composer_update") {
        // Run composer update
        sh 'composer update'
    }
    stage("unittest") {
        // Run PHPUnit
        sh 'vendor/bin/phpunit'
    }
    // Create new deployment assets
    switch (env.BRANCH_NAME) {
        case "master":
            stage("deploycode") {
                sh 'rsync -avzhP --exclude=.git/ $WORKSPACE/ root@192.168.1.112:/var/www/html/'
                sh 'ssh root@192.168.1.112 "chown -R nginx:nginx /var/www/html"'
            }
            break
        case "develop":
            stage("deploycode") {
                sh 'rsync -avzhP --exclude=.git/ $WORKSPACE/ root@192.168.10.111:/var/www/html/'
                sh 'ssh root@192.168.1.111 "chown -R nginx:nginx /var/www/html"'
            }
            break
        default:
            // No deployments for other branches
            break
    }
}
